sudo: required
language: python
services:
  - docker

install:
  - pip install ansible molecule=2.2.0 docker-py

script:
  - molecule test

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
