---
- name: import ubuntu tasks when target host is ubuntu
  import_tasks: ubuntu.yml
  when:
    - ansible_distribution == 'Ubuntu'
- name: import CentOS/Red Hat tasks when host is CentOS/REL
  import_tasks: centos.yml
  when:
    - ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux'
- name: import ArchLinux tasks when host is Archlinux
  import_tasks: archlinux.yml
  when:
    - ansible_distribution == 'Archlinux'
- name: clone shinobi ce
  git:
    dest: "{{ ansible_env.HOME }}/Shinobi"
    repo: "{{ ce_version }}"
    clone: true
    update: true
    version: "{{ shinobi_version }}"
  when: ce
  notify: restart shinobi

- name: clone shinobi pro
  git:
    dest: "{{ ansible_env.HOME }}/Shinobi"
    repo: "{{ pro_version }}"
    clone: true
    update: true
    version: "{{ shinobi_version }}"
  when: pro
  notify: restart shinobi

- name: copy super user credentials
  template:
    dest: "{{ ansible_env.HOME }}/Shinobi/super.json"
    src: super.json.j2
  notify: restart shinobi

- name: define master key when is not defined and cluster is enabled
  set_fact:
    master_key: "{{ random_key }}"
  when: cluster and (master_key is not defined)

- name: copy configuration
  template:
    dest: "{{ ansible_env.HOME }}/Shinobi/conf.json"
    src: conf.json.j2

- name: remove sqlite dependency when not lts
  lineinfile:
    path: "{{ ansible_env.HOME }}/Shinobi/package.json"
    state: absent
    regexp: '\"sqlite3\"'
  when: not lts

- name: Install npm requirements
  become: true
  npm:
    path: "{{ ansible_env.HOME }}/Shinobi"

- name: Install pm2
  become: true
  npm:
    name: pm2
    global: true
    state: present

- name:  Get users table
  command: mysql -h {{ db_host }} -u {{ shinobi_user }} -p{{ shinobi_pass }} {{ db_name }} -Ns -e "SHOW TABLES LIKE 'Users'"
  register: users_table
  changed_when: false

- name: Load Database
  mysql_db:
    name: "{{ db_name }}"
    state: import
    login_host: "{{ db_host }}"
    login_user: "{{ shinobi_user }}"
    login_password: "{{ shinobi_pass }}"
    target: "{{ ansible_env.HOME }}/Shinobi/sql/framework.sql"
  when: users_table.stdout == ""

- name: Start shinobi camera
  shell: pm2 start camera.js
  args:
    chdir: "{{ ansible_env.HOME }}/Shinobi"
  changed_when: "command_result.rc == 0"
  register: command_result
  failed_when: "command_result.rc != 0 and 'Script already launched' not in command_result.stderr"

- name: Start shinobi cron when is on the master node
  command: pm2 start cron.js
  args:
    chdir: "{{ ansible_env.HOME }}/Shinobi"
  when: (cluster and cluster_role=="master") or (not cluster)
  changed_when: "command_result.rc == 0"
  register: command_result
  failed_when: "command_result.rc != 0 and 'Script already launched' not in command_result.stderr"

- name: Start shinobi at boot
  shell:
    cmd: pm2 save && pm2 startup
    creates: /etc/systemd/system/pm2-root.service
  args:
    chdir: "{{ ansible_env.HOME }}/Shinobi"
  when: startup
